### ISSUE TITLE
Замечания по работе 3.1. Добавляем на страницу новые блоки

### ISSUE THREAD

**Issue by Und3rMySk1n** [Marakery/front_end#1]
1. Div с id="menu" получился нулевой высоты. 

2. В html-коде присутствует javascript.
```
<a href="javascript:void(0);" class="icon" onclick="myFunction()">
```

3. Опечатка в названии класса.
```
<div class="header_imgage"></div>
```

4. Заглавные буквы в названии картинки.
```
<img src="media/one_photo.PNG" alt="Photo" class="my_photo">
```

5. ex1, ex2 и ex3 - плохие названия для id-шников.

6. Проблемы с выравниванием CSS: есть лишние пустые строки, скобки написаны в египетской нотации. Не соответствует Code convention по CSS.

7. Толщина заголовков "Любимые писатели" и "Любимые сериалы" не совпадает с дизайном.

**Comment by Marakery** [comment]
Fixed
