### ISSUE TITLE
Замечания по работе 3.2. Верстка формы обратной связи

### ISSUE THREAD

**Issue by Und3rMySk1n** [Marakery/front_end#2]
**Замечания по коду:**
1. Инлайновые стили.
```
<textarea id="subject" name="subject" placeholder="Ваше сообщение.." style="height:150px"></textarea>
```

2. У input'ов не проставлены label'ы.

**Замечания по внешнему виду:**
1. В обычном состоянии border у полей ввода должен быть светло-сервый (#c9c9c9), при наведении - темно-серый (#a6a6a6). Зеленым он должен становиться тогда, когда мы на него нажимаем и начинаем вводить текст.

2. При наведении на выпадающий список или на слово (мужской/женский), курсор должен меняться на "палец".

**Comment by Marakery** [comment]
Fixed

**Comment by Marakery** [comment]
@Und3rMySk1n
Всё пофиксил
