### ISSUE TITLE
Замечания по работе 4.1 Задать поведение блокам для различных устройств/размеров экрана

### ISSUE THREAD

**Issue by Und3rMySk1n** [Marakery/front_end#3]
**Замечания по коду:**
1. Исправить все замечания по HTML из предыдущей лабы.

2. Исправить замечания по CSS из предыдущей лабы (пробелмы с выравниванием, не соблюдается Code convention).

3. Медиазапросы нужно писать от большего к меньшему, например:
```
@media screen and (max-width: 980px) 
{
    ...
}

@media screen and (max-width: 640px) 
{
    ...
}
```
Иначе они будут конфликтовать друг с другом. Стили, объявленные ниже, будут перекрывать стили, написанные выше.

**Замечания по внешнему виду:**
1. Страница ломается на ширине экрана: 980px, 822px, 815px.

2. Не надо скрывать элементы для мобильников (например, списки) - у нас не так много элементов на странице, чтобы их скрывать. Вместо этого нужно придумать как грамотно их расположить.

3. На разрешении меньше 1000px появляется горизонтальная прокрутка.

4. Элементы страницы не должны прижиматься к краям экрана на мобильнике. Это относится к блоку с фильмами и форме.

5. Между фильмами нет вертикального отступа, нужно добавить (когда фильмы располагаются в 1 или 2 колонки).

6. На разрешении 810px и ниже ломается заголовок для блока с формой (Напиши мне).

**Comment by Marakery** [comment]
Fixed
