### ISSUE TITLE
Замечания по работе 5.1 Основы JavaScript

### ISSUE THREAD

**Issue by Und3rMySk1n** [Marakery/front_end#4]
1. jQuery можно отключить, про нее будет в следующей лабораторной работе.

2. reverseStr - не лучшее название, нужно обойтись без сокращений в названии функции.

3. Функции не должны сами ничего выводить в консоль. Функция возвращает результат - мы выводим его в консоль.
```
function withoutLast(str) {
    console.log(str.slice(0, -1));
    return str;
}
```

4. Непонятное название аргумента. Сюда может передаваться любая строка, нужно дать осмысленное название аргументу.
```
function withoutSpaces(hi)
```

5. Функция кроме лишних пробелов удаляет пробелы перед запятой. Отлично! Тогда давай добавим удаление пробела не только перед запятой, но еще и перед остальными знаками препинания. А то сейчас с запятой работает, а с точкой или восклицательным знаком - нет.
```
function withoutSpaces(hi) {
    var newStr = hi.trim().replace(/\s+/g, " ").replace(/ ,\s/g,", ");
    console.log(newStr);
}
```

6. В коде используем одинарные кавычки.

**Comment by Marakery** [comment]
Done
